apiVersion: apps/v1
kind: Deployment

metadata:
 name: myapp


spec:

 replicas: 3

 selector:
  matchLabels:
   app: myapp


 template:

  metadata:
   labels:
    app: myapp


  spec:

   containers:

   - name: nginx

     image: srushti22/myapp:v2
     imagePullPolicy: Never

     ports:
     - containerPort: 80
